:terms:
    - :id: http://rdaregistry.info/termList/layout/1003
      :uri: http://rdaregistry.info/termList/layout/1003
      :term: back to back
    - :id: http://rdaregistry.info/termList/layout/1004
      :uri: http://rdaregistry.info/termList/layout/1004
      :term: bar by bar
    - :id: http://rdaregistry.info/termList/layout/1005
      :uri: http://rdaregistry.info/termList/layout/1005
      :term: bar over bar
    - :id: http://rdaregistry.info/termList/layout/1006
      :uri: http://rdaregistry.info/termList/layout/1006
      :term: both sides
    - :id: http://rdaregistry.info/termList/layout/1017
      :uri: http://rdaregistry.info/termList/layout/1017
      :term: double line spacing
    - :id: http://rdaregistry.info/termList/layout/1001
      :uri: http://rdaregistry.info/termList/layout/1001
      :term: double sided
    - :id: http://rdaregistry.info/termList/layout/1007
      :uri: http://rdaregistry.info/termList/layout/1007
      :term: line by line
    - :id: http://rdaregistry.info/termList/layout/1008
      :uri: http://rdaregistry.info/termList/layout/1008
      :term: line over line
    - :id: http://rdaregistry.info/termList/layout/1009
      :uri: http://rdaregistry.info/termList/layout/1009
      :term: melody chord system
    - :id: http://rdaregistry.info/termList/layout/1010
      :uri: http://rdaregistry.info/termList/layout/1010
      :term: open score
    - :id: http://rdaregistry.info/termList/layout/1011
      :uri: http://rdaregistry.info/termList/layout/1011
      :term: outline
    - :id: http://rdaregistry.info/termList/layout/1012
      :uri: http://rdaregistry.info/termList/layout/1012
      :term: paragraph
    - :id: http://rdaregistry.info/termList/layout/1013
      :uri: http://rdaregistry.info/termList/layout/1013
      :term: section by section
    - :id: http://rdaregistry.info/termList/layout/1014
      :uri: http://rdaregistry.info/termList/layout/1014
      :term: short form scoring
    - :id: http://rdaregistry.info/termList/layout/1015
      :uri: http://rdaregistry.info/termList/layout/1015
      :term: single line
    - :id: http://rdaregistry.info/termList/layout/1002
      :uri: http://rdaregistry.info/termList/layout/1002
      :term: single sided
    - :id: http://rdaregistry.info/termList/layout/1016
      :uri: http://rdaregistry.info/termList/layout/1016
      :term: vertical score
