:terms:
    - :id: http://rdaregistry.info/termList/soundCont/1002
      :uri: http://rdaregistry.info/termList/soundCont/1002
      :term: silent
    - :id: http://rdaregistry.info/termList/soundCont/1001
      :uri: http://rdaregistry.info/termList/soundCont/1001
      :term: sound
