:terms:
    - :id: http://rdaregistry.info/termList/trackConfig/1001
      :uri: http://rdaregistry.info/termList/trackConfig/1001
      :term: centre track
    - :id: http://rdaregistry.info/termList/trackConfig/1002
      :uri: http://rdaregistry.info/termList/trackConfig/1002
      :term: edge track
