:terms:
    - :id: http://rdaregistry.info/termList/noteMove/1009
      :uri: http://rdaregistry.info/termList/noteMove/1009
      :term: action stroke dance notation
    - :id: http://rdaregistry.info/termList/noteMove/1008
      :uri: http://rdaregistry.info/termList/noteMove/1008
      :term: Beauchamp-Feuillet notation
    - :id: http://rdaregistry.info/termList/noteMove/1007
      :uri: http://rdaregistry.info/termList/noteMove/1007
      :term: Benesh movement notation
    - :id: http://rdaregistry.info/termList/noteMove/1006
      :uri: http://rdaregistry.info/termList/noteMove/1006
      :term: DanceWriting
    - :id: http://rdaregistry.info/termList/noteMove/1005
      :uri: http://rdaregistry.info/termList/noteMove/1005
      :term: Eshkol-Wachman movement notation
    - :id: http://rdaregistry.info/termList/noteMove/1004
      :uri: http://rdaregistry.info/termList/noteMove/1004
      :term: game play notation
    - :id: http://rdaregistry.info/termList/noteMove/1010
      :uri: http://rdaregistry.info/termList/noteMove/1010
      :term: Kinetography Laban
    - :id: http://rdaregistry.info/termList/noteMove/1002
      :uri: http://rdaregistry.info/termList/noteMove/1002
      :term: Labanotation
    - :id: http://rdaregistry.info/termList/noteMove/1001
      :uri: http://rdaregistry.info/termList/noteMove/1001
      :term: Stepanov dance notation
