:terms:
    - :id: http://rdaregistry.info/termList/fontSize/1001
      :uri: http://rdaregistry.info/termList/fontSize/1001
      :term: giant print
    - :id: http://rdaregistry.info/termList/fontSize/1003
      :uri: http://rdaregistry.info/termList/fontSize/1003
      :term: jumbo braille
    - :id: http://rdaregistry.info/termList/fontSize/1002
      :uri: http://rdaregistry.info/termList/fontSize/1002
      :term: large print
