:terms:
    - :id: http://rdaregistry.info/termList/RDAColourContent/1002
      :uri: http://rdaregistry.info/termList/RDAColourContent/1002
      :term: monochrome
    - :id: http://rdaregistry.info/termList/RDAColourContent/1003
      :uri: http://rdaregistry.info/termList/RDAColourContent/1003
      :term: polychrome
