:terms:
    - :id: http://rdaregistry.info/termList/bookFormat/1014
      :uri: http://rdaregistry.info/termList/bookFormat/1014
      :term: 128mo
    - :id: http://rdaregistry.info/termList/bookFormat/1004
      :uri: http://rdaregistry.info/termList/bookFormat/1004
      :term: 12mo
    - :id: http://rdaregistry.info/termList/bookFormat/1005
      :uri: http://rdaregistry.info/termList/bookFormat/1005
      :term: 16mo
    - :id: http://rdaregistry.info/termList/bookFormat/1010
      :uri: http://rdaregistry.info/termList/bookFormat/1010
      :term: 18mo
    - :id: http://rdaregistry.info/termList/bookFormat/1006
      :uri: http://rdaregistry.info/termList/bookFormat/1006
      :term: 24mo
    - :id: http://rdaregistry.info/termList/bookFormat/1007
      :uri: http://rdaregistry.info/termList/bookFormat/1007
      :term: 32mo
    - :id: http://rdaregistry.info/termList/bookFormat/1011
      :uri: http://rdaregistry.info/termList/bookFormat/1011
      :term: 36mo
    - :id: http://rdaregistry.info/termList/bookFormat/1008
      :uri: http://rdaregistry.info/termList/bookFormat/1008
      :term: 48mo
    - :id: http://rdaregistry.info/termList/bookFormat/1002
      :uri: http://rdaregistry.info/termList/bookFormat/1002
      :term: 4to
    - :id: http://rdaregistry.info/termList/bookFormat/1009
      :uri: http://rdaregistry.info/termList/bookFormat/1009
      :term: 64mo
    - :id: http://rdaregistry.info/termList/bookFormat/1012
      :uri: http://rdaregistry.info/termList/bookFormat/1012
      :term: 72mo
    - :id: http://rdaregistry.info/termList/bookFormat/1003
      :uri: http://rdaregistry.info/termList/bookFormat/1003
      :term: 8vo
    - :id: http://rdaregistry.info/termList/bookFormat/1013
      :uri: http://rdaregistry.info/termList/bookFormat/1013
      :term: 96mo
    - :id: http://rdaregistry.info/termList/bookFormat/1001
      :uri: http://rdaregistry.info/termList/bookFormat/1001
      :term: folio
    - :id: http://rdaregistry.info/termList/bookFormat/1015
      :uri: http://rdaregistry.info/termList/bookFormat/1015
      :term: full-sheet
