:terms:
    - :id: http://rdaregistry.info/termList/frequency/1013
      :uri: http://rdaregistry.info/termList/frequency/1013
      :term: annual
    - :id: http://rdaregistry.info/termList/frequency/1014
      :uri: http://rdaregistry.info/termList/frequency/1014
      :term: biennial
    - :id: http://rdaregistry.info/termList/frequency/1007
      :uri: http://rdaregistry.info/termList/frequency/1007
      :term: bimonthly
    - :id: http://rdaregistry.info/termList/frequency/1003
      :uri: http://rdaregistry.info/termList/frequency/1003
      :term: biweekly
    - :id: http://rdaregistry.info/termList/frequency/1001
      :uri: http://rdaregistry.info/termList/frequency/1001
      :term: daily
    - :id: http://rdaregistry.info/termList/frequency/1016
      :uri: http://rdaregistry.info/termList/frequency/1016
      :term: irregular
    - :id: http://rdaregistry.info/termList/frequency/1008
      :uri: http://rdaregistry.info/termList/frequency/1008
      :term: monthly
    - :id: http://rdaregistry.info/termList/frequency/1010
      :uri: http://rdaregistry.info/termList/frequency/1010
      :term: quarterly
    - :id: http://rdaregistry.info/termList/frequency/1012
      :uri: http://rdaregistry.info/termList/frequency/1012
      :term: semiannual
    - :id: http://rdaregistry.info/termList/frequency/1009
      :uri: http://rdaregistry.info/termList/frequency/1009
      :term: semimonthly
    - :id: http://rdaregistry.info/termList/frequency/1005
      :uri: http://rdaregistry.info/termList/frequency/1005
      :term: semiweekly
    - :id: http://rdaregistry.info/termList/frequency/1006
      :uri: http://rdaregistry.info/termList/frequency/1006
      :term: three times a month
    - :id: http://rdaregistry.info/termList/frequency/1002
      :uri: http://rdaregistry.info/termList/frequency/1002
      :term: three times a week
    - :id: http://rdaregistry.info/termList/frequency/1011
      :uri: http://rdaregistry.info/termList/frequency/1011
      :term: three times a year
    - :id: http://rdaregistry.info/termList/frequency/1015
      :uri: http://rdaregistry.info/termList/frequency/1015
      :term: triennial
    - :id: http://rdaregistry.info/termList/frequency/1004
      :uri: http://rdaregistry.info/termList/frequency/1004
      :term: weekly
