:terms:
    - :id: http://rdaregistry.info/termList/recMedium/1001
      :uri: http://rdaregistry.info/termList/recMedium/1001
      :term: magnetic
    - :id: http://rdaregistry.info/termList/recMedium/1002
      :uri: http://rdaregistry.info/termList/recMedium/1002
      :term: magneto-optical
    - :id: http://rdaregistry.info/termList/recMedium/1003
      :uri: http://rdaregistry.info/termList/recMedium/1003
      :term: optical
