:terms:
    - :id: http://rdaregistry.info/termList/typeRec/1001
      :uri: http://rdaregistry.info/termList/typeRec/1001
      :term: analog
    - :id: http://rdaregistry.info/termList/typeRec/1002
      :uri: http://rdaregistry.info/termList/typeRec/1002
      :term: digital
