:terms:
    - :id: http://rdaregistry.info/termList/formatNoteMus/1001
      :uri: http://rdaregistry.info/termList/formatNoteMus/1001
      :term: choir book
    - :id: http://rdaregistry.info/termList/formatNoteMus/1002
      :uri: http://rdaregistry.info/termList/formatNoteMus/1002
      :term: chorus score
    - :id: http://rdaregistry.info/termList/formatNoteMus/1003
      :uri: http://rdaregistry.info/termList/formatNoteMus/1003
      :term: condensed score
    - :id: http://rdaregistry.info/termList/formatNoteMus/1004
      :uri: http://rdaregistry.info/termList/formatNoteMus/1004
      :term: part
    - :id: http://rdaregistry.info/termList/formatNoteMus/1005
      :uri: http://rdaregistry.info/termList/formatNoteMus/1005
      :term: piano conductor part
    - :id: http://rdaregistry.info/termList/formatNoteMus/1006
      :uri: http://rdaregistry.info/termList/formatNoteMus/1006
      :term: piano score
    - :id: http://rdaregistry.info/termList/formatNoteMus/1007
      :uri: http://rdaregistry.info/termList/formatNoteMus/1007
      :term: score
    - :id: http://rdaregistry.info/termList/formatNoteMus/1008
      :uri: http://rdaregistry.info/termList/formatNoteMus/1008
      :term: study score
    - :id: http://rdaregistry.info/termList/formatNoteMus/1009
      :uri: http://rdaregistry.info/termList/formatNoteMus/1009
      :term: table book
    - :id: http://rdaregistry.info/termList/formatNoteMus/1010
      :uri: http://rdaregistry.info/termList/formatNoteMus/1010
      :term: violin conductor part
    - :id: http://rdaregistry.info/termList/formatNoteMus/1011
      :uri: http://rdaregistry.info/termList/formatNoteMus/1011
      :term: vocal score
