:terms:
    - :id: http://rdaregistry.info/termList/grooveWidth/1001
      :uri: http://rdaregistry.info/termList/grooveWidth/1001
      :term: coarse groove
    - :id: http://rdaregistry.info/termList/grooveWidth/1002
      :uri: http://rdaregistry.info/termList/grooveWidth/1002
      :term: microgroove
