:terms:
    - :id: http://rdaregistry.info/termList/groovePitch/1005
      :uri: http://rdaregistry.info/termList/groovePitch/1005
      :term: fine
    - :id: http://rdaregistry.info/termList/groovePitch/1006
      :uri: http://rdaregistry.info/termList/groovePitch/1006
      :term: standard
