---
authority:
  service: direct
search:
  #------------------
  # Connection tests
  #------------------
  -
    query: 'Barack Obama'
  #------------------
  #  Accuracy tests
  #------------------
  -
    query: Volleyball
    position: 9000
    subject_uri: 'http://dbpedia.org/resource/Volleyball'
  -
    query: Cristiano Ronaldo
    position: 10
    subject_uri: 'http://dbpedia.org/resource/Cristiano_Ronaldo'
term:
  -
    identifier: 'http://dbpedia.org/resource/Barack_Obama'
